import '../styles/globals.css'
import type { AppProps } from 'next/app'
import Head from 'next/head'
function MyApp({ Component, pageProps }: AppProps) {
  
  <Head>
    <title>Aquecimento Global: O que é, suas consequências e como reduzir o impacto ambiental </title>
    <link rel="preconnect" href="https://fonts.googleapis.com" /> 
      <link rel="preconnect" href="https://fonts.gstatic.com" />
  <meta name="description" content="Generated by create next app" />
  <link rel="icon" href="/favicon.ico" />
  </Head>
  return <Component {...pageProps} />
}

export default MyApp
