/* eslint-disable @next/next/no-page-custom-font */
import '../styles/globals.css'
import type { AppProps } from 'next/app'
import Head from 'next/head'
function MyApp({ Component, pageProps }: AppProps) {
  
  
  return (
    <>
    <Head>
    <title>Aquecimento Global: O que é, suas consequências e como reduzir o impacto ambiental </title>
    <link rel="preconnect" href="https://fonts.googleapis.com" /> 
      <link rel="preconnect" href="https://fonts.gstatic.com" />
      <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@500;600;800&family=Nunito+Sans&display=swap" rel="stylesheet" />
  <meta name="description" content="Generated by create next app" />
  <link rel="icon" href="/favicon.ico" />
  </Head>
  <Component {...pageProps} />
  </>
  )

  
}

export default MyApp
